all:
   hosts:
    127.0.0.1:4567:
      ansible_ssh_host-127.0.0.1:
      ansible_ssh_port=22:
      ansible_ssh_user=vagrant:
      ansible_ssh_private_key_file=~/.ssh/known_hosts:
   children:
     nodes:
       hosts:
         127.0.0.1:5678
